name: TesJe
version: '1.0'
main: com.rnno.tesJe.TesJe
api-version: '1.21'
commands:
  hello:
    description: Send a Greeting
    usage: /<command> [player]
  wand:
    description: Get a Magic Staff
    usage: /<command>
  menu:
    description: Open a Menu
    usage: /<command>